### ISSUE TITLE
App does not work when Google Home/Assistant integration is on

### ISSUE THREAD

**Issue by Frankwin** [DaveGut/Test-Code#1]
I cannot get the App to work at all if the Google Home/Assistant integration on Hubitat is on. I actually wasn't even able to turn the Google Home integration on (using Google Assistant on my phone) while I had the TP-Link devices and App added to my Hubitat. On advice of Hubitat support I removed all the TP-Link devices and the App and once I did I was able to get the Google Home integration working, but now that it is working, I can no longer add my TP-Link devices with the App. I get to the point where I can select the devices, but once that dropdown box closes, it just jumps to the "Apps" screen.

Steps to reproduce:
1. Install the Google Home App (connect your Hubitat hub in Google Assistant on your phone and it'll install the Google Home App on the hub) - This step didn't even work for me while I had the TP-Link Devices and App installed, so make sure they're not.
2. Add the TP-Link Custom Devices + Custom App code
3. Install the TP-Link Smart Home Device Manager
4. Open the TP-Link Smart Home Device Manager
5. Click "Install Kasa Devices"
6. Select one or more devices from the drop down list (I had 23 populated)
7. Click "Done"
8. Screen goes back to the "Apps" tab, but no Device were added in the Devices tab

Hubitat support mentioned that they saw a lot of UDP traffic that they attributed to the interference w/ the Google Home App.

**Comment by DaveGut** [comment]
Sorry for the delay.  I am more responsive on the Hubitat blog section.

I do not use Google Home, so I can not try to replicate.

**Resolution data needed.**  I need log data to resolve the current problem to determine why you are not discovering the devices.  Before you do this, please load the latest Application version.

**Alternative.**  As an alternative, do a manual installation of the drivers.  You will then load the deviceIP in preferences and save.  It is also recommended that you set a static IP address for the device; however, that is not an absolute requirement.

**UDP usage**.  UDP is used a lot during the device discovery process.  Because TP-Link does not have a "discovery" capability, I poll each IP using UDP.  Discovery is used in two instances:

- At starting the Application it is run 1 time.
- If there is a device comms error (unable to reach the device), discovery is run a maximum of once every 10 minutes until the comms error is not reported.  The comms error is encountered only if the device IP has changed or the device is not present.

**Future:**  This week, I will be uploading version 4.1 of the drivers and application.  This version streamlines the processing and eliminates the IP update called from the driver to the app.  Instead, it will prompt the user to run the app or remove the device to resolve the error.

**Comment by DaveGut** [comment]
Just updated the app and device drivers to reducing the UDP polling.  It will now only poll when the application is started by the user.  This will last for about 15 seconds at that time.  All other udp traffic is based on user-controlled refresh rates, rule machine calls, and other items.

Closing issue.  If you still have google home problems, it is beyond the scope of this integration fixes.  You can manually install the devices.
