### ISSUE TITLE
quick polling not functioning in Kasa EM plug

### ISSUE THREAD

**Issue by johnbhill4** [DaveGut/Test-Code#11]
quick polling of Kasa EM Plug was not working
I removed the ! operator from the condition on line 292 of DeviceDrivers/TP-LinkEM-Plug(Hubitat).groovy and it seems to be running correctly now

**Comment by DaveGut** [comment]
Thanks for the concern.  For quick polling to work for energy monitor, you have to select the enable EM function in preferences and save.  If EM function is enabled, then the Power Quick poll will occur.  Otherwise, the ON/OFF poll will occur.  If you upgraded, part of the upgrade instructions were to update your preferences.  I guess I was not explicit enough on this issue.

**Comment by DaveGut** [comment]
Just tested using my multi-plug driver (exact same code in this area).  Quick Poll works as expected.
Dave
