### ISSUE TITLE
I had problems registering my HS110 .. had to change the deviceType in the driver

### ISSUE THREAD

**Issue by rummyr** [DaveGut/Test-Code#2]
If I tried to register my HS110 I got an error from the app.
com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'TP-Link Engr Mon Plug' in namespace 'davegut' not found on line 333 (installed)

I hacked in 	
   def deviceType() { return "Engr Mon Plug" }
and now it shows .. 

Just raising as this seems like a quick thing to change to allow partial functionality.

I can see the energy monitoring part hasn't yet been ported from the ST version, so not expecting energy monitoring - if I have time I'll try and do that and create a pull request, but time is limited unfortunately.

**Comment by DaveGut** [comment]
There was an upload error into Hubitat.  The EM Plug device handler is now present in the repository.

I am closing this issue; however, I do rely on users to verify the functionality.  It is NOT the same as on SmartThings since I was unable to obtain some of the data from the plugs.

Issue:  Hubitat does not support multiple responses from the same request.  TP-Link will break up the enrypted response string when the length is above some length.  This causes an error in parsing the data which is partial only.
